# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
jobs:
  # Additionaly
  build_and_test:
    # The 'if' condition is added here.
    # It checks if the current ref (branch or tag) matches the 'develop' branch
    # OR if the ref starts with 'feature/'
    if: |
      github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
    
    # Define the rest of your job steps here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script (This will only run on develop or feature/*)
        run: echo "Running build for develop or feature branch"
      
      # Add more steps like npm install, build, test, etc.
               - name: PDM update dependencies
  # You may pin to the exact commit or the version.
  # uses: pdm-project/update-deps-action@22852fcff9a131d732730e8db92cc9502643a260
  uses: pdm-project/update-deps-action@v1.12
  with:
    # A personal access token
    token: # optional, default is ${{ github.token }}
    # The commit message
    commit-message: # optional, default is chore: Update pdm.lock
    # The PR title
    pr-title: # optional, default is chore: Update pdm.lock
    # The update strategy, can be 'reuse', 'eager' or 'all'
    update-strategy: # optional, default is reuse
    # The save strategy, can be 'compatible', 'wildcard', 'exact' or 'minimum'
    save-strategy: # optional, default is minimum
    # Ignore the version constraint of packages in pyproject.toml
    unconstrained: # optional, default is false
    # Whether install PDM plugins before update
    install-plugins: # optional, default is false
    # Whether commit message contains signed-off-by
    sign-off-commit: # optional, default is false
    # Sign commits as github-actions[bot]
    sign-commits: # optional, default is true
           
