name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        java-version: [11, 17]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Run JUnit tests
      run: mvn test
    - name: Run JUnit tests
      run: mvn test

    - name: Upload JUnit Test Reports
      if: always() # Ensures reports are uploaded even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: junit_reports_java_${{ matrix.java-version }}
        path: target/surefire-reports  
